### ISSUE TITLE
FPM crashes when the backup created is applied 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#65]
## Preconditions
- Firefox Profile Manager is installed.
- Firefox is installed. 

## Steps to reproduce
1. Open FPM and create a new backup.
2. Go to Firefox and change the settings -> close the browser.
3. Go to FPM and swipe from left to right for the backup added at step 1.
4. Tap on "Apply". 

### Expected behavior
The backup is applied. 

### Actual behavior
The FPM crashes. 

- Logcat:
**01-13 11:42:51.889 870-870/? D/BatteryMeterView: ACTION_BATTERY_CHANGED : level:100 status:3 health:2
01-13 11:42:52.019 16948-16962/? I/art: Background sticky concurrent mark sweep GC freed 323(37KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 71MB/71MB, paused 2.685ms total 113.922ms
01-13 11:42:52.169 16948-16948/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fpm_nightly, PID: 16948
    java.lang.ArrayIndexOutOfBoundsException: length=8; index=-13
        at org.mozilla.fpm.data.BackupRepositoryImpl.getFileSignature(BackupRepositoryImpl.kt:75)
        at org.mozilla.fpm.data.BackupRepositoryImpl.getAll(BackupRepositoryImpl.kt:167)
        at org.mozilla.fpm.presentation.mvp.MainPresenter$getBackups$1$backups$1.invokeSuspend(MainPresenter.kt:26)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)**

**Note:**
- On devices with android >5, the backup is duplicated with "-temp" extension added to the name. 

### Device information
* Android device: Samsung Galaxy Tab A 6(Android 5.1.1), Huawei Honor 8 (Android 7.0), Sony Xperia Z5 Premium (Android 7.1.1) .
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
This seems to have been the result of just a bad build.
The underlying issue was that the local secret key used for encrypting / decrypting was not of 8 bytes as the DES algorithm requires.
So nothing really to patch here, just need to make sure that when building one is using a *valid* secret key.

For though improving on the current solution Andrei pushed a speculative fix for resolving concurrency issues which might arise when doing multiple encrypt / decrypt operations and I also cleaned the code a bit, improved documentation and introduced a validity check for the secret key at compile time.

**Comment by sflorean** [comment]
Verified as fixed on FPM build 7.
Devices:
- Motorola Moto G6 (Android 8.0),
- Huawei Honor 8 (Android 7.0),
- HTC Desire 820 (Android 6.0.1),
- Samsung Galaxy Tab A 6 (Android 5.1.1).
