### ISSUE TITLE
FPM crashes with OutOfMemoryError when applying backups

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#74]
## Preconditions:
Have backups from Fennec Beta/Nightly saved on Drive. 
## Steps to reproduce
1. Launch Firefox Profile Manager for Release;
2. Tap the "Import" button and choose from Drive the backups from Fennec Beta/Nightly;
3. Tap the "Apply" button for one of the imported backup from step 2;
### Expected behavior
The backup is applied on Release.
### Actual behavior
FPM crashes.

Logcat:
2020-01-28 14:20:40.933 22867-22867/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fpm, PID: 22867
    java.lang.OutOfMemoryError: Failed to allocate a 37775104 byte allocation with 9431432 free bytes and 9210KB until OOM, target footprint 201326592, growth limit 201326592
        at kotlin.collections.CollectionsKt___CollectionsKt.toByteArray(_Collections.kt:969)
        at org.mozilla.fpm.data.BackupRepositoryImpl.deploy(BackupRepositoryImpl.kt:116)
        at org.mozilla.fpm.presentation.mvp.MainPresenter$applyBackup$1$1.invokeSuspend(MainPresenter.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
### Device information
* Android device: Google Pixel 3 (Android Q);
* Build Firefox Profile Manager v1.0 Build 5 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
Based on the logcat which shows that the app needed 37MB of RAM while the device only had 9MB left and after confirming with @ebalazs-sv that this issue is not reproducing on other devices this seems like a device issue.
Closing as such.

**Comment by sflorean** [comment]
Reproducible also on Samsung Galaxy Tab A 6 (Android 5.1.1) when trying to create a backup (Beta) and for apply (Release). 
Resource Monitor details (beta): M:669MB CPU 59% 1500MHz.

**Comment by ebalazs-sv** [comment]
Also reproducible on FPM Release with Xiaomi Mi4i (Android 5.0.2) when applying a backup.
Resource Monitor details: M:408MB CPU 97%

**Comment by Mugurell** [comment]
Seem this issue is more widespread than initially thought.
Reopening to investigate if there's anything we can do to mitigate the problem.

**Comment by Mugurell** [comment]
Waiting for a confirmation from QA that all looks good now.
Added a speculative fix for the OOM. Not much we can do giving that the app flow requires to do the archiving/unarchiving, crypting/decrypting in memory...

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM build 7 with the following devices:
- Google Pixel 3 (Android Q),
- Samsung Galaxy Tab A 6 (Android 5.1.1)
- Xiaomi Mi4i (Android 5.0.2)
I will close this issue. Thanks!
